version: "3.3"

services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    restart: always
    ports:
      - 8081:8080
      #el 50000 es para enganchar con un jenkins slave
      #- 50001:50000
    volumes:
      - ./persistent/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./persistent/jenkins-war:/usr/share/jenkins
      #esto ultimo es para actualizar facil los war
